# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170219_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
