# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170219_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
