# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170220_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Image.UserImage'),
        ),
    ]
