# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
